hotelbooking/hotelbooking/hotelbooking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('visitors.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotelbooking/hotelbooking/visitors/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', LoginView.as_view(template_name='mainpage/login.html',success_url = reverse_lazy('homepage')), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.UserUpdateView.as_view(), name='my_profile'),
    path('signup/', views.SignupView.as_view(), name='signup'),

]

hotelbooking/hotelbooking/visitors/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=100)
    profession = models.CharField(max_length=100)
    address = models.CharField(max_length=100, null=True)
    github = models.CharField(max_length=100, null=True)
    facebook = models.CharField(max_length=100, null=True)
    twitter = models.CharField(max_length=100, null=True)
    instagram = models.CharField(max_length=100, null=True)
    website = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, upload_to='profile_pics/')

    def pic(self):
        if self.image:

            return self.image.url
        else:
            return 'https://bootdey.com/img/Content/avatar/avatar6.png'


class Project(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    complete_percent = models.IntegerField(default=0)

    def div_color(self):
        if 20 > self.complete_percent:
            return 'danger'
        if 40 > self.complete_percent > 20:
            return 'warning'
        if 60 > self.complete_percent > 40:
            return 'info'
        if 80 > self.complete_percent > 60:
            return 'primary'
        else:
            return 'success'

hotelbooking/hotelbooking/visitors/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django import forms


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class ProfileCreateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone', 'profession']

class ProfileDataForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'github', 'website', 'facebook', 'instagram', 'twitter']

class ProfileSocialForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['github', 'website', 'facebook', 'instagram', 'twitter']

hotelbooking/hotelbooking/visitors/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from .forms import RegistrationForm, ProfileCreateForm, ProfileDataForm, ProfileSocialForm
from django.urls import reverse_lazy
from django.contrib.auth.models import User

# Create your views here.
def homepage(request):
    return render(request, 'mainpage/homepage.html')

class SignupView(CreateView):
    form_class = RegistrationForm
    success_url = reverse_lazy('homepage')
    template_name = 'mainpage/signup.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['profile_form'] = ProfileCreateForm(self.request.POST or None)
        print(context)
        return context

    def form_valid(self, form):
        profile_form = ProfileCreateForm(self.request.POST)
        if profile_form.is_valid():
            self.object = form.save()
            profile = profile_form.save(commit=False)
            profile.user = self.object
            profile.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        # same as above
        print('form is invalid')
        return super().form_invalid(form)


class UserUpdateView(UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email']
    template_name = 'mainpage/profile.html'
    success_url = reverse_lazy('my_profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['profile_form'] = ProfileDataForm(self.request.POST or None, instance=self.request.user.profile)
        context['social_form'] = ProfileSocialForm(self.request.POST or None, instance=self.request.user.profile)
        return context

    def get_object(self, queryset=None):
        # this will nullify the need for a pk in the url, by default get_object is the function in
        # detail views that requires a pk or slug
        return self.request.user

    def form_valid(self, form):
        # the kwarg instance=something  in the call to a modelform is imperative to having
        # the form update and object rather than create a new one
        social_form = ProfileSocialForm(self.request.POST, instance=self.request.user.profile)
        profile_form = ProfileDataForm(self.request.POST, self.request.FILES, instance=self.request.user.profile)
        forms = [social_form, profile_form]
        for other_form in forms:
            if not other_form.is_valid():
                return self.form_invalid(form)

        for other_form in forms:
            other_form.save()
        return super().form_valid(form)

hotelbooking/hotelbooking/visitors/templates/mainpage/homepage.html
{% extends 'partials/base.html' %}
{% block title %}
    Homepage
{% endblock %}

{% block content %}
<main class="container">
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">Welcome to Pratap Heritage</h1>
      <p class="lead my-3">Get Great Stay and wonderful food</p>
      <p class="lead mb-0"><a href="#" class="text-white fw-bold">Book Now</a></p>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">World</strong>
          <h3 class="mb-0">Featured post</h3>
          <div class="mb-1 text-muted">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">Design</strong>
          <h3 class="mb-0">Post title</h3>
          <div class="mb-1 text-muted">Nov 11</div>
          <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

        </div>
      </div>
    </div>
  </div>

  <div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        From the Firehose
      </h3>
    </div>
  </div>
</main>


{% endblock %}

hotelbooking/hotelbooking/visitors/templates/mainpage/login.html
{% extends 'partials/base.html' %}
{% load bootstrap5 %}

{% block title %}
Login
{% endblock %}
{% block content %}
<h1>Welcome to our Login page</h1>
<div class="col-6">
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% bootstrap_button "Save" button_type="submit" button_class="btn-success" %}
    </form>
</div>
{% endblock %}

hotelbooking/hotelbooking/visitors/templates/mainpage/profile.html
{% extends 'partials/base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}
    User | Profile
{% endblock %}

{% block css %}
<link href="{% static 'accounts/css/profile.css' %}">
{% endblock %}

{% block content %}

<! --- profile page taken from https://www.bootdey.com/snippets/view/profile-edit-data-and-skills#html --->

<div class="container">
<form method="post" enctype="multipart/form-data">
		<div class="main-body">
			<div class="row">
				<div class="col-lg-4">
					<div class="card">
						<div class="card-body">
							<div class="d-flex flex-column align-items-center text-center">
								<img src="{{ user.profile.pic }}" alt="Admin" class="rounded-circle p-1 bg-primary" width="110">
								<div class="mt-3">
									<h4>{{ user.get_full_name}}</h4>
									<p class="text-secondary mb-1">{{ user.profile.profession}}</p>
<!--									<p class="text-muted font-size-sm">{{ user.profile.address}}</p>-->
									<a class="btn btn-primary">Follow</a>
									<a class="btn btn-outline-primary">Message</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-8">
					<div class="card">
						<div class="card-body">

                                {% csrf_token %}
                                {% for field in form %}
							<div class="row mb-3">
								<div class="col-sm-3">
									<h6 class="mb-0">{{ field.label}}</h6>
								</div>
								<div class="col-sm-9 text-secondary">
                                    {% bootstrap_field field show_label=False %}
								</div>
							</div>
                                {% endfor %}
                            {% for field in profile_form %}
							<div class="row mb-3">
								<div class="col-sm-3">
									<h6 class="mb-0">{{ field.label}}</h6>
								</div>
								<div class="col-sm-9 text-secondary">
                                    {% bootstrap_field field show_label=False %}
								</div>
							</div>
                                {% endfor %}

							<div class="row">
								<div class="col-sm-3"></div>
								<div class="col-sm-9 text-secondary">
                                    <button type="submit" class="btn btn-primary px-4" >Save Changes</button>
								</div>
							</div>

						</div>
					</div>
<!--					<div class="row">-->
<!--						<div class="col-sm-12">-->
<!--							<div class="card">-->
<!--								<div class="card-body">-->
<!--									<h5 class="d-flex align-items-center mb-3">Project Status</h5>-->
<!--                                    {% for project in user.profile.project_set.all %}-->
<!--                                        <p>{{ project.name }}</p>-->
<!--                                        <div class="progress mb-3" style="height: 5px">-->
<!--                                            <div class="progress-bar bg-{{ project.div_color }}" role="progressbar" style="width: {{ project.complete_percent }}%" aria-valuenow="{{ project.complete_percent }}" aria-valuemin="0" aria-valuemax="100"></div>-->
<!--                                        </div>-->
<!--                                        {% empty %}-->
<!--                                        No projects to display-->
<!--                                    {% endfor %}-->

<!--								</div>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
				</div>
			</div>
		</div>
</form>
	</div>
{% endblock %}

hotelbooking/hotelbooking/visitors/templates/mainpage/signup.html
{% extends 'partials/base.html' %}
{% load bootstrap5 %}

{% block title %}
Login
{% endblock %}
{% block content %}
<h1>Welcome to our Signup page</h1>
<div class="col-6">
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% bootstrap_button "Save" button_type="submit" button_class="btn-success" %}
    </form>
</div>
{% endblock %}

hotelbooking/hotelbooking/visitors/templates/partials/base.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>Pratap Heritage | {%block title%} {%endblock%}</title>

{%include 'partials/navbar.html'%}


<div class="container my-4" id="content-container">
{% block content %}
{% endblock %}
</div>

{%include 'partials/footer.html'%}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

hotelbooking/hotelbooking/visitors/templates/partials/footer.html
{%block footer%}


<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">All Rights Reserverd with Pratap Heritage</span>
  </div>
</footer>

{%endblock%}

hotelbooking/hotelbooking/visitors/templates/partials/navbar.html
{%block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'homepage'%}">Pratap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>

                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link ">Hello  Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="nav-link ">Login</a>
                </li>

                {%endif%}


        </div>
    </div>
</nav>
{%endblock%}