cardsgame/cardsgame/cardsgame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('forum/', include('forum.urls')),
    path('game/', include('game.urls')),
]

cardsgame/cardsgame/forum/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='forum_page'),
    #path('add_comment', views.CommentsCreateView.as_view(), name='comment_section'),
    path('add_comment/<int:post_id>', views.CommentsCreateView.as_view(), name='add_comment'),
    path('new_post/new_post', views.PostCreateView.as_view(), name='create_post'),
]

cardsgame/cardsgame/game/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('my_cards', views.my_cards, name='my_cards'),
    path('transfer/<int:id>', views.transfer, name='transfer'),
    path('homepage', views.homepage, name='homepage'),
    path('transaction/<int:id>', views.transaction, name='transaction'),
]

cardsgame/cardsgame/forum/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Forum_post(models.Model):
    title = models.CharField(max_length=100)
    post = models.CharField(max_length=1000, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    forum_post_author = models.ForeignKey(User,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)


class Comment_post(models.Model):
    #forum = models.ForeignKey(Forum_post, blank=True, on_delete=models.CASCADE, related_name='comments')
    forum = models.ForeignKey(Forum_post, blank=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)
    comment_author = models.ForeignKey(User,blank=True,on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.forum)

cardsgame/cardsgame/forum/forms.py
from django import forms
from .models import Forum_post, Comment_post


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Forum_post
        exclude = ['date_created', 'forum_post_author']


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment_post
        exclude = ['comment_author', 'forum']

cardsgame/cardsgame/forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, ListView
from .models import Forum_post, Comment_post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import PostModelForm, CommentModelForm


class CommentListView(ListView):
    model = Comment_post
    context_object_name = 'comments'
    template_name = 'forum_page1.html'


class PostListView(ListView):
    model = Forum_post
    context_object_name = 'posts'
    template_name = 'forum_page1.html'

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Forum_post
    form_class = PostModelForm
    success_url = reverse_lazy('forum_page')
    template_name = 'new_post.html'


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.forum_post_author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get(self,  request, *args, **kwargs):
        print(request.user)
        return super().get(request, *args, **kwargs)

class CommentsCreateView(LoginRequiredMixin, CreateView):
    model = Comment_post
    form_class = CommentModelForm
    success_url = reverse_lazy('forum_page')
    template_name = 'add_comment.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.comment_author = self.request.user
        post_id = self.kwargs['post_id']
        forum = Forum_post.objects.get(id=post_id)
        self.object.forum = forum
        self.object.save()
        return super().form_valid(form)

    def get(self,  request, *args, **kwargs):
        print(request.user)
        return super().get(request, *args, **kwargs)

cardsgame/cardsgame/forum/templates/add_comment.html
{%extends 'partials/base.html'%}
{%load bootstrap5%}
{%block title%}Comment{%endblock%}
{%block content%}
<div class="col-md-6 mx-auto">
    <form method="post" class="form">
  {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

    </div>
{%endblock%}

cardsgame/cardsgame/forum/templates/forum_page.html
{%extends 'partials/base.html'%}
{%load bootstrap5%}
{%block title%}Forum{%endblock%}
{%block content%}
<div class="col-md-6 mx-auto">
    <form method="post" class="form">
  {% csrf_token %}
        This is a Forum page
        <ul>
      {%for post in posts%}
       <li> {{post.title}}</li>
       <li> {{post.post}}</li>
       <li> {{post.date_created}}</li>
       <li> {{post.forum_post_author}}</li>

            {%for comment in post.comments.all%}
            {{comment}}

            {%endfor%}


            </ul>
        {%endfor%}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

    </div>
{%endblock%}

cardsgame/cardsgame/forum/templates/forum_page1.html
{%extends 'partials/base.html'%}
{%load bootstrap5%}
{% load static %}
<link rel="stylesheet" href="forum_page_style.css">

{%block title%}Forum{%endblock%}
{%block content%}

{%block css%}
<link rel="stylesheet" href="{% static './forum_page_style.css' %}" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css"
      integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous"/>

<link rel="stylesheet" href="./forum_page_style.css" type="text/css">
<link rel="stylesheet" href="./forum_page_style.css" type="text/css">
{%endblock%}
<div class="container">
    <div class="main-body p-0">
        <div class="inner-wrapper">
            <!-- Inner sidebar -->
            <div class="inner-sidebar">
                <!-- Inner sidebar header -->
                <div class="inner-sidebar-header justify-content-center">

                    <a href="{%url 'create_post'%}" class="btn btn-primary btn-sm active" role="button"
                       aria-pressed="true">+ New Discussion</a>

                    <h1>Post here for discussions</h1>
                </div>
                <!-- Forum List -->
                {%for post in posts%}

                <div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
                    <div class="card mb-2">
                        <div class="card-body p-2 p-sm-3">
                            <div class="media forum-item">
                                <a href="#" data-toggle="collapse" data-target=".forum-content"><img
                                        src="https://bootdey.com/img/Content/avatar/avatar1.png"
                                        class="mr-3 rounded-circle" width="50" alt="User"/></a>
                                <div class="media-body">
                                    <h6><a href="#" data-toggle="collapse" data-target=".forum-content"
                                           class="text-body">{{post.title}}</a></h6>
                                    <p class="text-secondary">
                                        {{post.post}}
                                    </p>
                                    <p class="text-muted"><a href="javascript:void(0)">{{post.forum_post_author}}</a>
                                        replied <span class="text-secondary font-weight-bold">{{post.date_created|timesince}} ago</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                        {{comments}}
                        {%for comment in post.comment_post_set.all%}

                        <div class="inner-main-body col-offset-6 p-2 p-sm-3 collapse forum-content show">
                            <div class="card mb-2">
                                <div class="card-body p-2 p-sm-3">
                                    <div class="media forum-item">
                                        <div class="media-body">
                                            <p class="text-secondary">
                                                {{comment.comment}}
                                            </p>
                                            <p class="text-secondary">
                                                Author: {{comment.comment_author}}
                                            </p>
                                            <p class="text-secondary">
                                                {{comment.date_created|timesince}}
                                            </p>
                                        </div>

                                    </div>
                                </div>
                                {%endfor%}
                            </div>
                            <a href="{%url 'add_comment' post.id%}" class="btn btn-secondary btn-sm active"
                               role="button"
                               aria-pressed="true">Leave Comment</a>

                        </div>


                    </div>


                    <!-- /Forum Detail -->

                    <!-- /Inner main body -->
                </div>

                <!-- /Inner main -->
            </div>{%endfor%}

            <!-- New Thread Modal -->
            <div class="modal fade" id="threadModal" tabindex="-1" role="dialog" aria-labelledby="threadModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <form>
                            <div class="modal-header d-flex align-items-center bg-primary text-white">
                                <h6 class="modal-title mb-0" id="threadModalLabel">New Discussion</h6>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="threadTitle">Title</label>
                                    <input type="text" class="form-control" id="threadTitle"
                                           placeholder="Enter title"
                                           autofocus=""/>
                                </div>
                                <textarea class="form-control summernote" style="display: none;"></textarea>

                                <div class="custom-file form-control-sm mt-3" style="max-width: 300px;">
                                    <input type="file" class="custom-file-input" id="customFile" multiple=""/>
                                    <label class="custom-file-label" for="customFile">Attachment</label>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                                <button type="button" class="btn btn-primary">Post</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    {%endblock%}

cardsgame/cardsgame/forum/templates/new_post.html
{%extends 'partials/base.html'%}
{%load bootstrap5%}
{%block title%}Forum{%endblock%}
{%block content%}
<div class="col-md-6 mx-auto">
    <form method="post" class="form">
  {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

    </div>
{%endblock%}